baseurl = "https://navaneeth.github.io/"
languageCode = "en-us"
title = "{love to code}"
theme = "hyde-x"
pygmentsuseclasses = "true"

[author]
    name = "nkn"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    github = "https://github.com/navaneeth/"
    tagline = "{love to code}"
    twitter = "http://twitter.com/navaneethkn"
    flickr = "https://www.flickr.com/photos/navaneethkn"
    rss = "true"
    highlight = "sunburst"
    home = "blog"
    googleAnalytics = "UA-38544003-1"

[[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about/"
